### ISSUE TITLE
Respect state of deleted or hidden fe_user

### ISSUE THREAD

**Issue by funkyferdy** [xperseguers/t3ext-oidc#13]
When a frontend_user was deleted local on typo3 and you re-login with the "same" user over oidc, the deleted record is updated (groups etc) but remains "deleted". But a Login is still possible. 
--> Suggestion: Should be handled as it never had existed --> Create a new FE-User-Record.

When a frontend_user was changed to hidden on typo3 and you re-login with the "same" user over oidc, the hidden record is updated (groups etc) but no login is possible. 
--> Suggestion: Should be also set to "unhidden" aka "reactivated".

Makes sense?

**Comment by xperseguers** [comment]
## deleted

Could you please explain why a deleted record should not be simply recovered? What's the purpose of creating a blank new one?

## updated

sure, makes sense.

**Comment by funkyferdy** [comment]
> Deleted
@xperseguers : You're right. It makes more sense to just set to "undeleted" again. So when there are relations to it, they will persist. If the fe_user.record was completely deleted (not only marked as deleted) it will be created like a new one.

**Comment by funkyferdy** [comment]
Testing login in a hidden user results in "login error", user record in BE remains "hidden".
=> Expected, unhidde user and log in

Testing login in a deleted user results in "login error", user record in BE remains "deleted".
=> Expected, undelete and unhide user and log in

**Comment by funkyferdy** [comment]
Forget my previous comment @xperseguers !
I forgot to activate options in extension config. everything works like expected!
