### ISSUE TITLE
Make mapping of Fields from OICD to FE_User configurable (in Backend)

### ISSUE THREAD

**Issue by funkyferdy** [xperseguers/t3ext-oidc#14]
Something like:

array.business_phone => fe_user.myfieldintypo3table

**Comment by xperseguers** [comment]
Since it's all about frontend and not backend, this can be done with TypoScript configuration. Setup is normally not (yet) available during authentication but it's not a big deal to access it anyway so that mapping can be fetched.

**Comment by xperseguers** [comment]
Problem is as follows on pre-production:

![exception](https://cloud.githubusercontent.com/assets/646805/25838130/ceb079f8-3491-11e7-98a8-089f3f3fc5bd.png)
