### ISSUE TITLE
Exception: Call to protected method Azure::getDefaultScopes() from scope Causal\Oidc\Service\OAuthService

### ISSUE THREAD

**Issue by wazum** [xperseguers/t3ext-oidc#148]
Exception 
```
Call to protected method TheNetworg\OAuth2\Client\Provider\Azure::getDefaultScopes() from scope Causal\Oidc\Service\OAuthService

causal/oidc/Classes/Service/OAuthService.php line 111
```

is thrown when trying to log in with username and password (from default login form for users that log in locally without an external system).

TYPO3 11
PHP 8.2
Extension version 2.1.0

**Comment by liayn** [comment]
Indeed there is a mismatch in visibility.

https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L382
declares this method protected, whereas
https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/GenericProvider.php#L185
has it public.

Once you use a different provider, which keeps the visibility like it should be, this fails:
https://github.com/xperseguers/t3ext-oidc/blob/master/Classes/Service/OAuthService.php#L111

Introduced with https://github.com/xperseguers/t3ext-oidc/commit/a8a5aa7f8580512b539124923e22cc856833f1aa
with issue #15

@xperseguers This looks to me to be some specific thing in regards to WSO only. I would suggest to use a dedicated provider in that case and remove the line in our code here. What do you think?

**Comment by xperseguers** [comment]
> @xperseguers This looks to me to be some specific thing in regards to WSO only. I would suggest to use a dedicated provider in that case and remove the line in our code here. What do you think?

Sounds like a fair move.

**Comment by liayn** [comment]
Since this workaround has been introduced some time ago, I'll first check if the underlying client has changed and maybe even sends the scopes in the meantime, which would make this obsolete in general.

**Comment by liayn** [comment]
> I'll first check if the underlying client has changed

No, it did not.

So my proposed patch is probably okay for the time being.
We don't know how many other IdPs actually require a scope for the password grant, maybe it's not only WSO2.

**Comment by liayn** [comment]
One more update here. At least Microsoft requires a scope here too.
