### ISSUE TITLE
Login does not work but produces 404 error

### ISSUE THREAD

**Issue by carsten-wilhelm** [xperseguers/t3ext-oidc#157]
We included the extension in TYPO3 V11 - the login button works and shows the OpenID login screen.
After logging in, we end up on the redirect page (the login page) and the URL contains a code and a state.

Debugging showed that the type 1489657462 was added to the query params of the request in the OauthCallback::process method. But the AuthenticationController (which is assigned to the type) does not get called.

We included the Typoscript and the type is showing up in backend template analyzer as well.

Any idea why we do not get a proper login page?

**Comment by carsten-wilhelm** [comment]
Found the issue - I had to add this to my config:

`        $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] = array_merge(
            $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'],
            [
                'code', 'state', 'sfdc_community_url', 'sfdc_community_id'
            ]
        );
`

**Comment by liayn** [comment]
Interesting finding.

Nevertheless, the latest master-version does not have the controller anymore and does all the stuff directly in the middleware. This should probably resolve this issue "auto-magically".

**Comment by liayn** [comment]
No feedback for some time. Closing this issue
