### ISSUE TITLE
felogin integration causes a request to the IdP on every login page request

### ISSUE THREAD

**Issue by liayn** [xperseguers/t3ext-oidc#158]
With the felogin event listener in place, the authorization url is generated, whenever the felogin is shown in FE.
This causes undesired load to the IdP and delays page rendering.

Depending on the actual provider (for instance Azure), additional requests are made, delaying page rendering further. This ultimately may lead to rate limiting by the IdP, which is the worst-case.

**First suggestion:**
Since there is a viewhelper in place to generate the authorization url, I suggest dropping the felogin-event completely. So people can use felogin, without being affected by this extension at all. (would be a breaking change)

**Second suggestion:**
Instead of creating the authorization url directly in the viewhelper, we should create a link to a middleware, which then creates the authorization url and redirects. Moreover, the generated link should include a `rel=nofollow`.

**Comment by xperseguers** [comment]
I like the second approach, generating the URL only when actually needed.

**Comment by liayn** [comment]
I'll push a PR for both. We can leave the first one pending, until we reach a new major version of the ext.

**Comment by liayn** [comment]
https://github.com/xperseguers/t3ext-oidc/pull/159 now runs in production and works flawlessly

**Comment by liayn** [comment]
Since #159 is merged, I'm closing this for now.
