### ISSUE TITLE
Register and login with Keycloak

### ISSUE THREAD

**Issue by NimaJa1372** [xperseguers/t3ext-oidc#160]
I have several users defined in my Keycloak server, and I would like to enable them to register and login to the TYPO3 frontend without requiring a frontend user in TYPO3. In other words, I don't have any website users defined in my frontend. The only available registration and login method would be through keycloak. Is this possible with this extension?

**Comment by xperseguers** [comment]
No, you need a Frontend user in TYPO3 so that the inherent concept of "authentication" works in TYPO3. If you don't "do" anything with those created Frontend users, it's up to you, but you will have to live with Frontend user records created in your TYPO3 website.

**Comment by NimaJa1372** [comment]
Does this extension automatically create frontend users in TYPO3? In other terms, if a Keycloak user tries to log in to the TYPO3 frontend, will a user with the same name and information be created in TYPO3?

**Comment by xperseguers** [comment]
That’s the whole point of having an external authentication, don’t you think? 🤔

So of course! And if you read the documentation, there’s nowhere explaining that you are supposed to create users before they can authenticate…

**Comment by NimaJa1372** [comment]
I have seen some other extensions that allow only existing frontend users to add external authentication to their accounts. However, these extensions do not work if there is no pre-existing account (For example: OAuth2 Login Client (backend and frontend). That is why I asked.
