### ISSUE TITLE
Redirect problems using keycloak

### ISSUE THREAD

**Issue by DSchneekloth** [xperseguers/t3ext-oidc#161]
I am using a OIDC setup with Keycloak. However the redirects (from keycloack back) are causing trouble. 

1. The initial redirect after the login (to an authenticated users only page) only seems to work if the OIDC Redirect setting is left blank and one specifies the Pid to be redirected to in typscript with plugin.tx_oidc_login.defaultRedirectPid. Is this intended?
2. A logged-in user may call the /login url and then be redirected to a white page with an url /login?logintype=login&tx_oidc[code]=... So far I have not been able to find an easy fix for this and there are no apparent errors in the logs for typo3 and php. This is especially confusing, as the redirect after the first login works (see 1.).

**Comment by liayn** [comment]
Which version do you use?

**Comment by DSchneekloth** [comment]
Typo3 12.4.16, OIDC is up to date with dev-main.

**Comment by liayn** [comment]
Hm. It might be unlikely to be related, but master branch does not declare v12 compatibility yet
https://github.com/xperseguers/t3ext-oidc/blob/master/composer.json

So I presume you somehow "made it work".

Are you referring to this setting?
https://github.com/xperseguers/t3ext-oidc/blob/master/ext_conf_template.txt#L23

You should probably not mangle this setting at all. It must point to some URL, where the normal FE-middleware chain is executed.
Maybe you can enable debug-logging and paste a trace here, so I can inspect the URLs generated?

**Comment by DSchneekloth** [comment]
We are using a modified fork of OIDC (sorry I didn't lead with that, I was only just made aware)
https://github.com/undkonsorten/t3ext-oidc/tree/typo3-12.4

there we are using the setting plugin.tx_oidc_login.defaultRedirectPid, also specified in it's documentation. The setting you linked, is the one we are leaving "blank", which was confusing (but did not cause apparent problems, i.e. on the first login)

And the strange thing is, in the log-file (var/log/typo3_*.log), there is nothing to be found about this problem.
Is there a way to obtain more information for example from log settings?

**Comment by liayn** [comment]
You can enable DEBUG log level. https://github.com/xperseguers/t3ext-oidc?tab=readme-ov-file#dedicated-log-file-for-openid-connect

What did you adjust in your fork? (short summary maybe, did not look into the code)

**Comment by DSchneekloth** [comment]
The fork was not created by us and there is a merge request into master currently https://github.com/xperseguers/t3ext-oidc/pull/144 I think it was only about 12.4 compatibility.

The Logs are indeed empty, and to specify the problem again, an already logged in user, calling a page with the oidc login plugin, gets an empty html page. I belive this is a bug.

A known workaround: Hide at login for the content piece OIDC login, add a Show at any login plain html with a redirect to a desired other page.

**Comment by DSchneekloth** [comment]
Oh yes, sorry. I think point 1 was only out of curiosity but not really relevant (unless it affects 2)

In my perspective a user who is logged in, but calls  /login (i.e. form a bookmark) should be redirected to the place they are redirected after the initial login (which is specified in the plugin and is related to part 1 of the question). Does that make sense?

**Comment by liayn** [comment]
> In my perspective a user who is logged in, but calls /login (i.e. form a bookmark) should be redirected to the place they are redirected after the initial login (which is specified in the plugin and is related to part 1 of the question). Does that make sense?

Makes sense, but the redirect target is not so straight forward, since we also support dynamic the `redirect_url`.
Still redirecting to the default target might cover the 90%-case.
Let's find a bugfix for that case.

**Comment by liayn** [comment]
@DSchneekloth please review the suggusted change
