### ISSUE TITLE
Compatibility with TYPO3 13

### ISSUE THREAD

**Issue by Starkmann** [xperseguers/t3ext-oidc#163]
We will be working on TYPO3 13 compatibility soon.

Are you planing to have a 12 **and** 13 compatible version, or will 13 be an extra version.

**Comment by liayn** [comment]
I'd be happy to have a version compatible v11 to v13, if doable.

**Comment by liayn** [comment]
So maybe can we combine this with #130 ?

**Comment by xperseguers** [comment]
Yes, I ensure "my" extensions are compatible with (at least) 2 LTS, more is even better, moreover for such kind of extensions where some extended support is best due to their usage in environments where updates are always more complex and a bit slower.
