### ISSUE TITLE
How to disable SSL verification in curl commands

### ISSUE THREAD

**Issue by dfineSvenFlock** [xperseguers/t3ext-oidc#166]
Hi,

I need a little help in some configuration of your extension: 

I am using LetsEncrypt staging certificates for my Keycloak instance in development. Thus, I am getting the following error due to not trustworthy SSL certificates when talking to the service:

<img width="1728" alt="Screenshot 2024-07-30 at 21 08 44" src="https://github.com/user-attachments/assets/3434c6bb-5793-4cde-be23-0dd02ed7dead">

I already googled for the problem but the usual trick doesn't work:

```php
<?php
$GLOBALS['TYPO3_CONF_VARS']['HTTP']['verify'] = false;
```

I have verified that the setting is properly applied. Thus, I think that the plugin does not take the global setting into account or must  be configured separately.  I am looking for the "-k" switch in curl in our extension.

Using official LetsEncrypt certificates work fine and no error is thrown.

Can you tell me which setting I have to make?

Thanks,
Sven

**Comment by liayn** [comment]
Hi! That's correct, we lack initialization of the provider in `GenericOAuthProviderFactory` with `$collaborators` where we can specify our own HTTP client (which would adhere to the TYPO3_CONF_VARS

**Comment by liayn** [comment]
@dfineSvenFlock please test my patch as linked above. (I did not test it)
If it works for you, I'll create a pull request.

**Comment by NimaJa1372** [comment]
We tested the patch.

The following error occurs on the page where the oidc plugin is embedded, and we are not redirected to the oidc server:
![image](https://github.com/user-attachments/assets/4acdc554-d5ab-44f9-9649-ee5b525bbfd1)

And this is the log:
`Wed, 31 Jul 2024 10:01:08 +0000 [ALERT] request="93d89ed278434" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 202407311001085c4c5b57- Exception: Too few arguments to function Causal\Oidc\Factory\GenericOAuthProviderFactory::__construct(), 0 passed in /var/www/clients/client0/web15/web/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php on line 2985 and exactly 1 expected, in file /var/www/clients/client0/web15/web/vendor/typo3/cms-frontend/Classes/ContentO>`

**Comment by liayn** [comment]
Okay, `GenericOAuthProviderFactory` needs to be public service.
I adjusted the patch (force pushed). Can you please try again?

**Comment by NimaJa1372** [comment]
Unfortunately it did not work. I get the same error

**Comment by liayn** [comment]
Did you clear caches via Install Tool?

**Comment by NimaJa1372** [comment]
I just did it. Now, i get this error:

`Wed, 31 Jul 2024 11:23:26 +0000 [ALERT] request="8bc66e39bec3e" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 202407311123264bd2dc42- Exception: Non-static method TYPO3\CMS\Core\Http\Client\GuzzleClientFactory::getClient() cannot be called statically, in file /var/www/clients/client0/web15/web/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php:722 - {"exception":"Error: Non-static method TYPO3\\CMS\\Core\\Http\\Client\\GuzzleClientFactory::getClient() cannot be called statically in /var/www/clients/client0/web15/web/packages/oidc/Classes/Factory/GenericOAuthProviderFactory.php:37\nStack trace:\n#0 /var/www/clients/client0/web15/web/packages/oidc/Classes/Service/OAuthService.php(229): Causal\\Oidc\\Factory\\GenericOAuthProviderFactory->create()\n#1 /var/www/clients/client0/web15/web/packages/oidc/Classes/Service/OAuthService.php(74): Causal\\Oidc\\Service\\OAuthService->getProvider()\n#2 /var/www/clients/client0/web15/web/packages/oidc/Classes/Controller/>`

**Comment by liayn** [comment]
Which TYPO3 version are you using? (v12 support is not yet official, my patch is v11 only)

**Comment by liayn** [comment]
The reason for you error is probably this breaking change in Core: https://review.typo3.org/c/Packages/TYPO3.CMS/+/73271/7/typo3/sysext/core/Classes/Http/Client/GuzzleClientFactory.php

**Comment by liayn** [comment]
I pushed a new version of the patch, which should also work with v12

**Comment by NimaJa1372** [comment]
I use v12. It works now. Thanks a lot!

**Comment by dfineSvenFlock** [comment]
@liayn Big thanks from my side as well! I will close the issue. Please make a PR and also we are quite looking into the PR for v12 support :-).
