### ISSUE TITLE
Use #[\SensitiveParameter] attribute for e.g. passwords

### ISSUE THREAD

**Issue by liayn** [xperseguers/t3ext-oidc#177]

**Comment by xperseguers** [comment]
Good idea! I did it for ig_ldap_sso_auth in v4.0 :)

**Comment by liayn** [comment]
That's were I found it ;-)

**Comment by xperseguers** [comment]
Yes, that sounds totally legit, those still in need for PHP 7.4 or PHP 8.0 can stick on the existing version, and the new version supporting v12, and possibly v13 requires PHP 8.1+, that's fair and in line with official support of PHP.

Switching to PHP 8.1+ allows to get much cleaner code, thus prone to good refactoring.

**Comment by liayn** [comment]
I'd go for PHP8.2 actually, because this attribute is supported since then only

**Comment by xperseguers** [comment]
No problem with PHP 8.1, it's just not taken into account, which doesn't hurt since it wasn't there for many versions either. And PHP 8.1 is in ELTS mode, thus I find it makes sense to keep support for it, since that extension doesn't target most up-to-date environments... https://www.php.net/supported-versions.php

**Comment by xperseguers** [comment]
indeed!

**Comment by liayn** [comment]
will prepare that now then.

**Comment by xperseguers** [comment]
IIRC it would even work with PHP 7.4 but would only require to be specified on a separate line with nothing afterwards as `#` is considered a comment for the reste of the line until 8.0 or 8.1 where `#[...]` is a special comment similar to `/* ... */`

**Comment by liayn** [comment]
Okay, I'd still argue 8.1 is okay to raise
