### ISSUE TITLE
500 Error on generating the authorization-URL (click on login-button {openidConnectUri}) via route oidc/authentication

### ISSUE THREAD

**Issue by wrock** [xperseguers/t3ext-oidc#185]
Thank you for this very cool extension and the effort and expertise you invest and share!

TYPO3 Version: 12.4.24
PHP: 8.1
causal/oidc: 3.0.0

User Story: On a fe-login-page the button to login via oidc is placed (to connect to Austria-ID). The URL of the button is generated correctly, same as in the previous version. Clicking the OIDC-Login-Button or calling the login-URL https://mysite.ddev.site/oidc/authentication?&validation_hash=a70efece5ffeb8481ce8adb5c3db4c2bb8f0c4b7&login_url=https%3A%2F%2Fmysite.ddev.site%2F&redirect_url=  then calls the AuthenticationUrlRequest.php-Middleware that generates the Auth-Context via the OpenIdConnectService . Here I find a propperly enriched request-object. 
After the call of $authorizationUrl = $this->OAuthService->getAuthorizationUrl($authorizationUrlOptions); in line 105 of OpenIdConnectService.php inside the  OAuthService.php the $GLOBALS['TYPO3_REQUEST'] only has 1 attribute (applicationType), but no site-attribute. So no DefaultLanguage can be fetched (call on null in line 75 of OAuthService.php).

I don't see, why the $GLOBALS['TYPO3_REQUEST'] is not enriched correctly. The $request object in the middleware was enriched correctly...

**Comment by liayn** [comment]
Thanks for the report and the debugging. Will take a look soon, what's going on here.

**Comment by liayn** [comment]
I pushed a possible fix, but didn't test it yet. Please let me know @wrock if this works for you.
