### ISSUE TITLE
Reminder Argument 3 passed to Causal\Oidc\Service\AuthenticationService::applyMapping() must be of the type array

### ISSUE THREAD

**Issue by funkyferdy** [xperseguers/t3ext-oidc#19]
Still Problem on login in with an user that does not exists yet.

Argument 3 passed to Causal\Oidc\Service\AuthenticationService::applyMapping() must be of the type array, boolean given, called in /var/www/webroot/ROOT/web/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php on line 175 

TypeError thrown in file
/var/www/webroot/ROOT/web/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php in line 312.

12 Causal\Oidc\Service\AuthenticationService::applyMapping("fe_users", array, boolean, array)

/var/www/webroot/ROOT/web/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php:
00173:                 'password' => $hashedPassword,
00174:                 'deleted' => 0,
00175:                 'disable' => 0,
00176:             ]
00177:         );

**Comment by xperseguers** [comment]
would you mind ```var_dump($row); die()``` on line 167?
