### ISSUE TITLE
SQL warning after first approval

### ISSUE THREAD

**Issue by xperseguers** [xperseguers/t3ext-oidc#3]
The first time you authenticate with OpenID Connect and allow your website to access your credentials, the call to `->getResourceOwner()` returns an array with a single key `sub` and its corresponding user ID but not the full list of attributes.

As such, the frontend user cannot be properly created.

**Comment by xperseguers** [comment]
![info](https://cloud.githubusercontent.com/assets/646805/24038460/c57195fc-0b01-11e7-8ddc-4a5bfb02d38f.png)

**Comment by funkyferdy** [comment]
ah well, so it seems that is a problem from our side with the claim, in theory it should you deliver more:

![grafik](https://cloud.githubusercontent.com/assets/22144187/24039534/e26d401c-0b05-11e7-90d8-fb37331917cb.png)

Let me check that

**Comment by xperseguers** [comment]
Yes, yesterday right before release 0.1.0 I got many info (but not as many as on your screenshot).

**Comment by funkyferdy** [comment]
ok, that was your other SP, i defined a new one for our explizit callback (needs) to be like this. Ca you check if you get more now?

**Comment by xperseguers** [comment]
no it does not help, I still only get `sub`

**Comment by funkyferdy** [comment]
@xperseguers: Will open a ticket/question to our integrator. il keep you updated!
