### ISSUE TITLE
Keep redirect URL from TYPO3

### ISSUE THREAD

**Issue by xperseguers** [xperseguers/t3ext-oidc#4]
The login form may have a redirect URL argument in the URL. Whenever OpenID Connect is used, this URL should be kept so that the user gets ultimately redirected to the proper page.

**Comment by funkyferdy** [comment]
that would be great!

1. try to access a restricted page like : sac-cas.ch/imhidden (keep that)
2. Initiate auth
3. come back from oidc (callback) and redirect to the (originally) keeped url
