### ISSUE TITLE
TYPO3 Exception: #1294587217: The page is not configured! [type=1489657462][]

### ISSUE THREAD

**Issue by ChrisMuc** [xperseguers/t3ext-oidc#40]
Hi!
I would love to use this plugin, but after discovernig and fixing a bug in felogin (https://github.com/TYPO3/TYPO3.CMS/pull/221), I got stuck with the following Exception:
Uncaught TYPO3 Exception: #1294587217: The page is not configured! [type=1489657462][]. This means that there is no TypoScript object of type PAGE with typeNum=1489657462 configured.

- I can click a button to get to my OpenID Connect IDP
- I can authenticate myself at the IDP and get redirected to <Typo3Page>/typo3conf/ext/oidc/callback.php?...
- callback.php redirects me to <Typo3Page>/?type=1489657462&...
But then the exception is thrown.

What did I do wrong? Can someone give me a hint?

**Comment by ChrisMuc** [comment]
Okay, I found the solution. Our page template did not include the static template configuration of this oidc-plugin.

**Comment by gopimallela** [comment]
Hi Chris, I encountered the same issue but could not solve it by including the oidc template. Do I have to write any additional typoscript in setup.
