### ISSUE TITLE
Is a self-signed certificate can be used by the oidc IDP ?

### ISSUE THREAD

**Issue by 0x0ff** [xperseguers/t3ext-oidc#45]
Hi,

I'm currently working on a dev environment and I'm wondering if a valid certificate is needed to works with this connector or if a self-signed one is enough.

Also I'm not very clear how to setup this extension tho. I understound that if I only need it for FeUser then felogin extension is not needed.

I've setup the plugin configuration with my endpoints/key/id, put the plugin OIDC record on the same page as the typo3 login form. Both object are configured with my "sso_users" container which is empty. But it doesn't work. :(

Regards,

**Comment by xperseguers** [comment]
old ticket, no clue like that, and ticketing system is for actual bugs, please ask the TYPO3 community for support.
