### ISSUE TITLE
Is it now possible to connect it with loadbalancer in between?

### ISSUE THREAD

**Issue by webfacer** [xperseguers/t3ext-oidc#46]
Hi, we have a loadbalancer in between. Should it be possible to login with your extension? because i tried and it failed because the loadbalancer is also in roundrobin mode. This means it is not the server where you logged in to, so i will never know which server is trying to resolve request.
If not do you have an idea or some attempts how it would be possible ro resolve loadbelancer issue.

**Comment by xperseguers** [comment]
I don't see exactly what the problem can be, possibly you should create a graphic explaining "where" your LB is located (TYPO3 / OIDC server etc) and maybe this resource helps you: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html

**Comment by webfacer** [comment]
Hi and Sorry for this issue, it was an issue on our side because of cookies sharing same domain. we had a subdomain for sharing cookies instead of just ".example.com" to be shareable within same domain.
