### ISSUE TITLE
Hook for access token

### ISSUE THREAD

**Issue by subnoodle** [xperseguers/t3ext-oidc#48]
Dear Xavier,

we use your extension for a third party software to have a login for FE-users-pages AS WELL to display user data from the third party system on the fe-users-pages in TYPO3.

For the second request, we have to retrieve data from the remote system.
Instead building a 2nd REST-API-login for the users data and so force the user to login twice, we could use the access token doing it via OAuth.
The third party system supports that explicitly:
[Cyclos OAuth Features](https://wiki4.cyclos.org/index.php/OpenID_Connect_-_OAuth2#Features_supported_in_Cyclos)

We investigates in the code and we found out that the access token is dropped after FE-user-login took place.

Do you see any chance for providing a hook / location to gain the access token before it's lost?

Any reply is highly appreciated.

Thank you very much, Thomas

**Comment by subnoodle** [comment]
Dear Xavier,

any hint about how to hook the access token or how to overwrite a class would be appreciated.

The basic idea is to modify method Causal\Oidc\Service\OAuthService\getAccessToken
by either overwriting it in our own extension (would that be possible with standard-typoscript?) or hooking it (must be an existing hook slot i guess, correct?).

The additional code will put user name and access token into the session.
Do you see any security issue doing this?

Thank you, Thomas

**Comment by xperseguers** [comment]
It doesn't sound like method `getAccessToken` needs to get a slot, but a slot would be useful in your case in the method calling that method.
