### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by Lumrenion** [xperseguers/t3ext-oidc#68]
Version 1.0.0 was released on 21. August 2020. Since then there have been 21 commits including bugfixes and features as well as compatibility with TYPO3 10. Some subjective highlights:
-  https://github.com/xperseguers/t3ext-oidc/commit/e9df1d6e2c125351a207b53520af4c83a3f9fefe
- https://github.com/xperseguers/t3ext-oidc/commit/f472772d4b9575efd135824283c3fa5632ff1af1
- https://github.com/xperseguers/t3ext-oidc/commit/2f95893aec654cd12031e14498146212d3d56758
- https://github.com/xperseguers/t3ext-oidc/commit/7407599af5800256cf756c9db879a9f1173b3c32

Is there something missing for a new release? Can we help with that?

**Comment by xperseguers** [comment]
Version 1.1.0 has been released in the mean time and version 1.2.0 is on its way :)
