### ISSUE TITLE
Login fails with TYPO3 10 if field mapping exists

### ISSUE THREAD

**Issue by SomeBdyElse** [xperseguers/t3ext-oidc#70]
We just updated our site to TYPO3 v10 and had the login fail with the following error message. 

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1561583122: TypoScriptFrontendController must be constructed with a valid Site object or a resolved site in the current request as fallback. None given. | InvalidArgumentException thrown in file /app/web/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php in line 775. Requested URL: https://www.….local/de/login/?redirect_url=%%2Fde%%2F&cHash=3b9ec8b8a0ed8a4d2b961d8815b0e8e2&logintype=login&tx_oidc[code]=…

The call stack of the exception lead to here: 
https://github.com/xperseguers/t3ext-oidc/blob/master/Classes/Service/AuthenticationService.php#L541

At this line, a fake TSFE is constructed with the intent to run extended ->stdWrap functions. The instantiation of the TSFE fails with the above error message.

**Comment by xperseguers** [comment]
@SomeBdyElse is it still a problem?

**Comment by liayn** [comment]
No feedback for a long time. Going to close this one.
