### ISSUE TITLE
Compatibility with other provider like Azure

### ISSUE THREAD

**Issue by r3h6** [xperseguers/t3ext-oidc#81]
This would help to make the extension work with ohter providers like Azure.
(Azure for example submits the roles only in the access token, they are not available through the userinfo endpoint)

**Comment by xperseguers** [comment]
Hello @r3h6, thanks for reporting, just had a quick look at your PR and it looks good actually.

Would you mind describing a bit more what you need(ed) to do in regard to Azure? That may be needed as well when it comes to using ADFS v4 as it looks like only a single and alone `sub` attribute is returned with `/userinfo`.

**Comment by r3h6** [comment]
Hello @xperseguers, the main problem as you already spotted, is the userinfo endpoint. The endpoint does not return any "roles", but they are in the id_token within the access token. What I did, was xclass the OAuthService and override the getResourceOwner method to return a GenericResourceOwner with "Roles".

With this commit https://github.com/xperseguers/t3ext-oidc/commit/e8228aeaba95605ae600fd3a3873263c6ff1149a it is hopefully possible to integrate specific provider packages depending on league/oauth2-client (
https://packagist.org/packages/league/oauth2-client/dependents?order_by=downloads) and not depending on xclass.

**Comment by liayn** [comment]
Is there anything left to do here?
Maybe documentation on how to configure this correctly for AD stuff?

I suspect this will be a major use case in the future, when all companies are migrating to cloud based ADs.

**Comment by liayn** [comment]
@r3h6 Can this be closed?

**Comment by r3h6** [comment]
@liayn Can be closed
