### ISSUE TITLE
Signal Slot "getUser" doesn't work with TYPO3 11

### ISSUE THREAD

**Issue by jagodzinski** [xperseguers/t3ext-oidc#91]
Hello,

when I try to use the getUser Signal Slot with TYPO3 11 I get following error:
"Cannot use positional argument after named argument during unpacking"

It works, if you make following change in Classes/Service/AuthenticationService.php Line 128
```
old: $dispatcher->dispatch(__CLASS__, 'getUser', ['user' => $user]);
new: $dispatcher->dispatch(__CLASS__, 'getUser', [$user]);
```

Regards
Jessica

**Comment by xperseguers** [comment]
Reading the source code of the method `->dispatch()` I don't get why you would get that error at this point. Could you please tell me where this error is actually thrown?

**Comment by jagodzinski** [comment]
The error is thrown in /var/www/html/vendor/typo3/cms-extbase/Classes/SignalSlot/Dispatcher.php line 144

$slotReturn = $callable(...$preparedSlotArguments);

I use TYPO3 11.5.24 and php 8.1

**Comment by xperseguers** [comment]
@liayn Can you possibly have a look at this one please?
